name: PyTest
on:
  push:
    branches:
      - "*" # TODO: run on all for now (move to main later)
  pull_request:
    branches:
      - "*"
jobs:
  run-pytest:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest test/
